export const invites = [
  { name: "Manel", userId: "INV-715C16" },
  { name: "Laura", userId: "INV-4C136B" },
  { name: "Pau", userId: "INV-2B5AB0" },
  { name: "Mariona", userId: "INV-3092B6" },
  { name: "Guillem", userId: "INV-D034C4" },
  { name: "Carla", userId: "INV-73FFFC" },
  { name: "Àvia Àngels", userId: "INV-77CB94" },
  { name: "Avi Salvador", userId: "INV-B83F73" },
  { name: "Àvia Anna", userId: "INV-A4663D" },
  { name: "Avi Manel", userId: "INV-7917EB" },
  { name: "Tieta Ester", userId: "INV-1060F2" },
  { name: "Artal", userId: "INV-9EDCBA" },
  { name: "Tiet Pep", userId: "INV-5BB77B" },
  { name: "Cristina", userId: "INV-2EB4B9" },
  { name: "Tieta Àngels", userId: "INV-72129A" },
  { name: "Tiet Manel", userId: "INV-8A8099" },
  { name: "Tieta Anna", userId: "INV-BB0AED" },
  { name: "Tiet Albert", userId: "INV-63C882" },
  { name: "Tiet Marc", userId: "INV-81BF50" },
  { name: "Tieta Susana", userId: "INV-E7AD50" },
  { name: "Albert", userId: "INV-BBF52B" },
  { name: "Aina", userId: "INV-89C90D" },
  { name: "Marta", userId: "INV-39CA04" },
  { name: "Aleix", userId: "INV-C42010" },
  { name: "Berta", userId: "INV-285394" },
  { name: "Martí", userId: "INV-886CE5" },
  { name: "Tere", userId: "INV-EEF220" },
  { name: "Vicente", userId: "INV-FF9894" },
  { name: "Loli", userId: "INV-A0DC21" },
  { name: "Pepi", userId: "INV-3E42F9" },
  { name: "Pedro", userId: "INV-53964B" },
  { name: "Màxim", userId: "INV-5EC7DA" },
  { name: "Chloe", userId: "INV-ED6BEC" },
  { name: "Salva", userId: "INV-C2D90E" },
  { name: "Alba", userId: "INV-931CFC" },
  { name: "Ernest", userId: "INV-D0006D" },
  { name: "Pau", userId: "INV-4525AE", plusOneName: "Oscar" },
  { name: "Dani", userId: "INV-6D5178" },
  { name: "Ángel", userId: "INV-B74A41" },
  { name: "Gloria", userId: "INV-B62E96" },
  { name: "Nito", userId: "INV-693DA6" },
  { name: "Mercé", userId: "INV-49F45D" },
  { name: "Tata", userId: "INV-A6D61D" },
  { name: "Tato", userId: "INV-750ADD" },
  { name: "Carme", userId: "INV-879C3D" },
  { name: "Gisela", userId: "INV-DA7506" },
  { name: "Fali", userId: "INV-EFA2D0" },
  { name: "Jose", userId: "INV-416531" },
  { name: "Desi", userId: "INV-624CD6" },
  { name: "Pepo", userId: "INV-F74F7B" },
  { name: "Ricard", userId: "INV-877E7A" },
  { name: "Sílvia", userId: "INV-71D319" },
  { name: "Didac", userId: "INV-9DFA17" },
  { name: "Carme", userId: "INV-1CCEE3" },
  { name: "Herminda", userId: "INV-9C676F" },
  { name: "Aitor", userId: "INV-26F759" },
  { name: "Aina", userId: "INV-9C851C" },
  { name: "Lesly", userId: "INV-7BF8FD" },
  { name: "Laurene", userId: "INV-80D69D" },
  { name: "Desi", plusOneName: "Miquel", userId: "INV-7F0556" },
  { name: "Lucía", plusOneName: "Baró", userId: "INV-C910ED" },
  { name: "Albert Rocafort", userId: "INV-1EC712" },
  { name: "Nico", userId: "INV-799F64" },
  { name: "Àlex", userId: "INV-360EB0" },
  { name: "Salvatore", userId: "INV-D8A792" },
  { name: "Iker", plusOneName: "Laura", userId: "INV-CFC0C7" },
  { name: "Samu", userId: "INV-B18043" },
  { name: "Alejandra", userId: "INV-841560" },
  { name: "John", userId: "INV-BDEA2B" },
  { name: "Carlo", userId: "INV-7F3921" },
  { name: "Joan", userId: "INV-8A8BB9" },
  { name: "Jordi", userId: "INV-AAC8C2" },
  { name: "Manel", userId: "INV-A70973" },
  { name: "Alberto F", userId: "INV-341A2F" },
  { name: "Clàudia", userId: "INV-BF1CB5" },
  { name: "Dosta", userId: "INV-F73FED" },
  { name: "Soriano", userId: "INV-A38FFA" },
  { name: "Marina", userId: "INV-8357A8" },
  { name: "Pablo", userId: "INV-B315FB" },
  { name: "Tati", userId: "INV-FFEFB2" },
  { name: "Marquitus", userId: "INV-C3538B" },
  { name: "Matt", userId: "INV-2FCCE2" },
  { name: "Pat", userId: "INV-9AB7E1" },
  { name: "Oriol Isern", plusOneName: "Núria", userId: "INV-1C86AD" },
  { name: "Valeria", userId: "INV-812F10" },
  { name: "Hector", plusOneName: "Olga", userId: "INV-44768E" },
  { name: "Ángela", userId: "INV-D663B3" },
  { name: "Adi", plusOneName: "Oleg", userId: "INV-6C45B3" },
  { name: "Jan", userId: "INV-8AF25E" },
  { name: "Xavo", userId: "INV-14A484" },
  { name: "Less", userId: "INV-F23039" },
  { name: "Tiet Joan", userId: "INV-D7D720" },
  { name: "Tieta Teresa", userId: "INV-C4413B" },
  { name: "Salva", userId: "INV-80EC0D" },
  { name: "Viqui", userId: "INV-9D3EA2" },
  { name: "Fina", userId: "INV-359337" },
  { name: "Tiet Fermín", userId: "INV-6BE713" },
  { name: "Tieta Anna", userId: "INV-9C4F12" },
  { name: "Tieta Glòria", userId: "INV-474B4C" },
  { name: "Jaume", userId: "INV-A28C27" },
  { name: "Eva", userId: "INV-3270A7" },
  { name: "Ribes", userId: "INV-B33873" },
  { name: "Remei", userId: "INV-3301BA" },
  { name: "Andrés", plusOneName: "Isabel", userId: "INV-BFA7E4" },
];
