export const invites = [
  { name: "Manel", userId: "INV-62B82B" },
  { name: "Laura", userId: "INV-F3EE47" },
  { name: "Pau", userId: "INV-3BEE05" },
  { name: "Mariona", userId: "INV-CEE2F5" },
  { name: "Guillem", userId: "INV-738A96" },
  { name: "Carla", userId: "INV-8A71C1" },
  { name: "Àvia Àngels", userId: "INV-9C85E4" },
  { name: "Avi Salvador", userId: "INV-2D2D52" },
  { name: "Àvia Anna", userId: "INV-2D49AF" },
  { name: "Avi Manel", userId: "INV-F97457" },
  { name: "Tieta Ester", userId: "INV-F11B0B" },
  { name: "Artal", userId: "INV-8D8CFC" },
  { name: "Tiet Pep", userId: "INV-BDEE78" },
  { name: "Cristina", userId: "INV-3E8A86" },
  { name: "Tieta Àngels", userId: "INV-3309F6" },
  { name: "Tiet Manel", userId: "INV-863212" },
  { name: "Tieta Anna", userId: "INV-982F7A" },
  { name: "Tiet Albert", userId: "INV-BF4BB2" },
  { name: "Tiet Marc", userId: "INV-6972D0" },
  { name: "Tieta Susana", userId: "INV-A0CD23" },
  { name: "Albert", userId: "INV-C8B445" },
  { name: "Aina", userId: "INV-7BCF0A" },
  { name: "Marta", userId: "INV-641988" },
  { name: "Aleix", userId: "INV-2EC130" },
  { name: "Berta", userId: "INV-87A428" },
  { name: "Martí", userId: "INV-B21161" },
  { name: "Tere", userId: "INV-2FCC92" },
  { name: "Vicente", userId: "INV-776F9B" },
  { name: "Loli", userId: "INV-C22DE6" },
  { name: "Pepi", userId: "INV-90C4EB" },
  { name: "Pedro", userId: "INV-5FEE0E" },
  { name: "Màxim", userId: "INV-1A4CE4" },
  { name: "Chloe", userId: "INV-C98251" },
  { name: "Salva", userId: "INV-8347B7" },
  { name: "Alba", userId: "INV-5C5753" },
  { name: "Ernest", userId: "INV-71691B" },
  { name: "Pau", userId: "INV-5617B2" },
  { name: "Dani", userId: "INV-1739C9" },
  { name: "Ángel", userId: "INV-4DEAA7" },
  { name: "Gloria", userId: "INV-A792DD" },
  { name: "Nito", userId: "INV-9EE7D4" },
  { name: "Mercé", userId: "INV-BE67B4" },
  { name: "Tata", userId: "INV-76C317" },
  { name: "Tato", userId: "INV-4F37BC" },
  { name: "Carme", userId: "INV-F4B696" },
  { name: "Gisela", userId: "INV-DD7A8E" },
  { name: "Fali", userId: "INV-AD0E3E" },
  { name: "Jose", userId: "INV-F4A0FF" },
  { name: "Desi", userId: "INV-D14AE8" },
  { name: "Pepo", userId: "INV-111A2D" },
  { name: "Ricard", userId: "INV-6137E7" },
  { name: "Sílvia", userId: "INV-372788" },
  { name: "Didac", userId: "INV-59E009" },
  { name: "Carme", userId: "INV-B7EA76" },
  { name: "Herminda", userId: "INV-212B66" },
  { name: "Aitor", userId: "INV-8975D4" },
  { name: "Aina", userId: "INV-42F0EF" },
  { name: "Lesly", userId: "INV-7008B7" },
  { name: "Laurene", userId: "INV-7B0A89" },
  { name: "Desi", plusOneName: "Miquel", userId: "INV-20EADA" },
  { name: "Lucía", plusOneName: "Baró", userId: "INV-21DBB7" },
  { name: "Albert Rocafort", userId: "INV-E269D6" },
  { name: "Nico", userId: "INV-59D5FC" },
  { name: "Àlex", userId: "INV-37ACC9" },
  { name: "Salvatore", userId: "INV-56B6FC" },
  { name: "Iker", plusOneName: "Laura", userId: "INV-9DB647" },
  { name: "Samu", userId: "INV-661F07" },
  { name: "Alejandra", userId: "INV-43F66C" },
  { name: "Jhon", userId: "INV-960EF3" },
  { name: "Carlo", userId: "INV-14FC9F" },
  { name: "Joan", userId: "INV-BBF683" },
  { name: "Jordi", userId: "INV-39A61F" },
  { name: "Manel", userId: "INV-D71C2D" },
  { name: "Alberto F", userId: "INV-14CFA0" },
  { name: "Clàudia", userId: "INV-C5E8E7" },
  { name: "Dosta", userId: "INV-B11136" },
  { name: "Soriano", userId: "INV-3761E5" },
  { name: "Marina", userId: "INV-3B20AC" },
  { name: "Pablo", userId: "INV-62F347" },
  { name: "Tati", userId: "INV-679AA9" },
  { name: "Marquitus", userId: "INV-507DB0" },
  { name: "Matt", userId: "INV-E36373" },
  { name: "Pat", userId: "INV-5AF931" },
  { name: "Oriol Isern", plusOneName: "Núria", userId: "INV-5B87FF" },
  { name: "Valeria", userId: "INV-E84E78" },
  { name: "Hector", plusOneName: "Olga", userId: "INV-3943C3" },
  { name: "Ángela", userId: "INV-EA5F38" },
  { name: "Adi", plusOneName: "Novio", userId: "INV-150B3B" },
  { name: "Jan", userId: "INV-EE7499" },
  { name: "Xavo", userId: "INV-E0724E" },
  { name: "Less", userId: "INV-CA0A25" },
  { name: "Tiet Joan", userId: "INV-C274BA" },
  { name: "Tieta Teresa", userId: "INV-24890A" },
  { name: "Salva", userId: "INV-57C95F" },
  { name: "Viqui", userId: "INV-DD1E8A" },
  { name: "Fina", userId: "INV-14FBE6" },
  { name: "Tiet Fermín", userId: "INV-58456C" },
  { name: "Tieta Anna", userId: "INV-F1463C" },
  { name: "Tieta Glòria", userId: "INV-A978C3" },
  { name: "Jaume", userId: "INV-E68994" },
  { name: "Eva", userId: "INV-B032DC" },
  { name: "Ribes", userId: "INV-C71036" },
  { name: "Remei", userId: "INV-12F117" },
];
