export const translations = {
  orioleva: `Oriol & Eva`,
  subtitle: `Dissabte 11 d'abril de 2026`,
  important_title: `Ei ei ei!`,
  important_title2: `Tenim **boda**!`,
  important_text: `Hola {nomConvidat}! Si has rebut aquest lloc web vol dir que ens fa molta il·lusió que ens acompanyis durant aquell dia. I perquè puguis organitzar-te et deixem els detalls més importants a continuació.`,
  important_details: `**Dissabte 11 d'abril de 2026**\nCerimonia religiosa a l'[esglèsia de Santa Maria de Llívia](https://share.google/gZrC0i61nemwl0KoJ)\nConvit, celebració i festa a [La Formatgeria de Llívia](https://www.laformatgeria.com/)`,
  cta_confirmation: `Confirmo que vinc!`,
  cta_important: `Important`,
  cta_location: `Ubicació`,
  cta_times: `Horari`,
  cta_present: `Regal`,
  cta_faqs: `FAQS`,
  locations_title: `Un decorat de pel·lícula`,
  locations_text: `La Cerdanya és un petit paradís al Pirineu, una vall oberta, pobles amb molta història i unes vistes d'infart. A nosaltres ens encanta fer-la servir com a camp base: a l'hivern ens passem els caps de setmana esquiant i després recuperant-nos davant de la llar de foc. A l'estiu us recomanem caminar per la muntanya, respirar aire ben net i gaudir d'uns paisatges (que com diu l'Eva) són dignes d'una pel·lícula.\n En vuit anys de relació hem viscut molts moments a la Cerdanya, hem gaudit de les coses que més ens agrada fer com a parella i compartit instants que no podrem oblidar mai amb amics i família. No ens imaginem un millor “spot” per fer oficial el nostre compromís. Sempre serà el nostre lloc segur al que tornar 🥰`,
  time_title: `Com serà aquell dia?`,
  time_text: `Et deixem un resum de quines coses farem.\n Però has de saber que és un **casament diürn amb un horari aproximat de 12:00h a 22:30h**`,
};
